spring.application.name=chatroom

#Server, port and path configuration
base.url=http://localhost
server.port=8080
server.servlet.context-path=/chatroom
#Link to the App : http://localhost:8080/chatroom

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/chatroom
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Enable debugging
# logging.level.org.springframework.boot.autoconfigure=DEBUG

#Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saad.test.apps@gmail.com
spring.mail.password=wcuj bema ccud xrfz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true